In [1]:
import adaboost

In [2]:
dataMat,classLabels = adaboost.loadSimpData()

In [3]:
dataMat

matrix([[ 1. ,  2.1],
        [ 2. ,  1.1],
        [ 1.3,  1. ],
        [ 1. ,  1. ],
        [ 2. ,  1. ]])

In [4]:
classLabels

[1.0, 1.0, -1.0, -1.0, 1.0]

In [5]:
from numpy import *

In [6]:
D = mat.(ones((5,1)))

SyntaxError: invalid syntax (<ipython-input-6-5926550960e9>, line 1)

In [7]:
D = mat(ones((5,1)))

In [8]:
D

matrix([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]])

In [9]:
adaboost.buildStump(dataMat,classLabels,D)

split: dim 0, thresh  0.90, thresh inequal: lt, the weighted error is 2.000
split: dim 0, thresh  0.90, thresh inequal: gt, the weighted error is 3.000
split: dim 0, thresh  1.00, thresh inequal: lt, the weighted error is 2.000
split: dim 0, thresh  1.00, thresh inequal: gt, the weighted error is 3.000
split: dim 0, thresh  1.10, thresh inequal: lt, the weighted error is 2.000
split: dim 0, thresh  1.10, thresh inequal: gt, the weighted error is 3.000
split: dim 0, thresh  1.20, thresh inequal: lt, the weighted error is 2.000
split: dim 0, thresh  1.20, thresh inequal: gt, the weighted error is 3.000
split: dim 0, thresh  1.30, thresh inequal: lt, the weighted error is 1.000
split: dim 0, thresh  1.30, thresh inequal: gt, the weighted error is 4.000
split: dim 0, thresh  1.40, thresh inequal: lt, the weighted error is 1.000
split: dim 0, thresh  1.40, thresh inequal: gt, the weighted error is 4.000
split: dim 0, thresh  1.50, thresh inequal: lt, the weighted error is 1.000
split: dim 0

({'dim': 0, 'ineq': 'lt', 'thresh': 1.3}, matrix([[ 1.]]), array([[-1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.]]))

In [10]:
classifierArray = adaboost.adaBoostTrainDS(dataMat,classLabels,9)

split: dim 0, thresh  0.90, thresh inequal: lt, the weighted error is 0.400
split: dim 0, thresh  0.90, thresh inequal: gt, the weighted error is 0.600
split: dim 0, thresh  1.00, thresh inequal: lt, the weighted error is 0.400
split: dim 0, thresh  1.00, thresh inequal: gt, the weighted error is 0.600
split: dim 0, thresh  1.10, thresh inequal: lt, the weighted error is 0.400
split: dim 0, thresh  1.10, thresh inequal: gt, the weighted error is 0.600
split: dim 0, thresh  1.20, thresh inequal: lt, the weighted error is 0.400
split: dim 0, thresh  1.20, thresh inequal: gt, the weighted error is 0.600
split: dim 0, thresh  1.30, thresh inequal: lt, the weighted error is 0.200
split: dim 0, thresh  1.30, thresh inequal: gt, the weighted error is 0.800
split: dim 0, thresh  1.40, thresh inequal: lt, the weighted error is 0.200
split: dim 0, thresh  1.40, thresh inequal: gt, the weighted error is 0.800
split: dim 0, thresh  1.50, thresh inequal: lt, the weighted error is 0.200
split: dim 0

In [11]:
classifierArray


[{'alpha': 0.6931471805599453, 'dim': 0, 'ineq': 'lt', 'thresh': 1.3},
 {'alpha': 0.9729550745276565, 'dim': 1, 'ineq': 'lt', 'thresh': 1.0},
 {'alpha': 0.8958797346140273,
  'dim': 0,
  'ineq': 'lt',
  'thresh': 0.90000000000000002}]

In [12]:
adaboost.adaClassify([0,0],classifierArray)

[[-0.69314718]]
[[-1.66610226]]
[[-2.56198199]]


matrix([[-1.]])

In [13]:
adaboost.adaClassify([[5,5],[0,0]],classifierArray)

[[ 0.69314718]
 [-0.69314718]]
[[ 1.66610226]
 [-1.66610226]]
[[ 2.56198199]
 [-2.56198199]]


matrix([[ 1.],
        [-1.]])