In [1]:
import bayes

listOPosts,listClasses = bayes.loadDataSet()

In [2]:
listOPosts

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posing', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [3]:
listClasses

[0, 1, 0, 1, 0, 1]

In [4]:
myVocabList = bayes.createVocabList(listOPosts)

In [5]:
myVocabList

['cute',
 'love',
 'maybe',
 'steak',
 'is',
 'to',
 'food',
 'flea',
 'dalmation',
 'him',
 'posing',
 'park',
 'help',
 'please',
 'mr',
 'dog',
 'worthless',
 'has',
 'I',
 'ate',
 'buying',
 'quit',
 'stupid',
 'not',
 'licks',
 'how',
 'problems',
 'stop',
 'so',
 'garbage',
 'my',
 'take']

In [6]:
bayes.setOfWords2Vec(myVocabList,listOPosts[0])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0]

In [7]:
bayes.setOfWords2Vec(myVocabList,listOPosts[4])

[0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0]

In [8]:
trainMat = []
for postinDoc in listOPosts:
    trainMat.append(bayes.setOfWords2Vec(myVocabList,postinDoc))
    
    

In [9]:
trainMat

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0],
 [0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1],
 [1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0],
 [0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]]

In [10]:
trainMat[0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0]

In [11]:
listClasses


[0, 1, 0, 1, 0, 1]

In [12]:
trainMat[5]

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [13]:
from numpy import *


In [14]:
mat(trainMat)

matrix([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
         0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
         1, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
         0, 0, 1, 1, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
p0v,p1v,pAb = bayes.trainNB0(trainMat,listClasses)

p0Denom = 26.000000
p1Denom = 21.000000


In [16]:
p0v

array([ 0.07692308,  0.07692308,  0.03846154,  0.07692308,  0.07692308,
        0.07692308,  0.03846154,  0.07692308,  0.07692308,  0.11538462,
        0.03846154,  0.03846154,  0.07692308,  0.07692308,  0.07692308,
        0.07692308,  0.03846154,  0.07692308,  0.07692308,  0.07692308,
        0.03846154,  0.03846154,  0.03846154,  0.03846154,  0.07692308,
        0.07692308,  0.07692308,  0.07692308,  0.07692308,  0.03846154,
        0.15384615,  0.03846154])

In [17]:
p1v

array([ 0.04761905,  0.04761905,  0.0952381 ,  0.04761905,  0.04761905,
        0.0952381 ,  0.0952381 ,  0.04761905,  0.04761905,  0.0952381 ,
        0.0952381 ,  0.0952381 ,  0.04761905,  0.04761905,  0.04761905,
        0.14285714,  0.14285714,  0.04761905,  0.04761905,  0.04761905,
        0.0952381 ,  0.0952381 ,  0.19047619,  0.0952381 ,  0.04761905,
        0.04761905,  0.04761905,  0.0952381 ,  0.04761905,  0.0952381 ,
        0.04761905,  0.0952381 ])

In [18]:
pAb

0.5

In [19]:
bayes.testingNB()

p0Denom = 26.000000
p1Denom = 21.000000
['love', 'my', 'dalmation'] classified as: 0
['stupid', 'garbage'] classified as: 1
